name: 'Deploy .NET MVC App'
description: 'Deploy the .NET MVC application to a server'
runs:
  using: 'composite'
  
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Build and Publish
      run: dotnet publish -c Release -o ./publish
      
    - name: Deploy to Server
      uses: pantaSanjesh/Portfolio@v1.0.0
      with:
        path: '/var/www/html'
